// Fill in  your WiFi networks SSID and password
#define SECRET_SSID "AndroidHotspotB3_F0_B6"
#define SECRET_PASS "s7096501"

// Fill in the hostname of your AWS IoT broker
#define SECRET_BROKER "av0uo8vn97cxt-ats.iot.ap-northeast-2.amazonaws.com"

// Fill in the boards public certificate
const char SECRET_CERTIFICATE[] = R"(
-----BEGIN CERTIFICATE-----
MIICijCCAXKgAwIBAgIVANkclGApS9FXs7rOxSX2yW1EAntmMA0GCSqGSIb3DQEB
CwUAME0xSzBJBgNVBAsMQkFtYXpvbiBXZWIgU2VydmljZXMgTz1BbWF6b24uY29t
IEluYy4gTD1TZWF0dGxlIFNUPVdhc2hpbmd0b24gQz1VUzAeFw0yMzA5MjAwMjQw
NTBaFw00OTEyMzEyMzU5NTlaMBkxFzAVBgNVBAMTDk15TUtSV2lGaTEwMTAgMFkw
EwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEv5kLDQHRGrHBWQUvb8MGxOgwWNT5RgQ9
5EX9VgLSEuf2QPzjTLI78OEtLn4UPzGwuOZ3Otf5s7weFT/uKOb3+qNgMF4wHwYD
VR0jBBgwFoAUlzs75aRhASIRrZAHz2PkPGIMUkUwHQYDVR0OBBYEFGh+aNhDYHwl
DHWNgcGOscY6vZD5MAwGA1UdEwEB/wQCMAAwDgYDVR0PAQH/BAQDAgeAMA0GCSqG
SIb3DQEBCwUAA4IBAQB+spn4CdBtXtZtMK8JB2GCsvroKoGtYVOrGiqy8qu+Zz/F
7FKw+aUTUvPmalXQRsxdfU43BOyPseycQIzgOI/LQO619PkpbVhBTKJ9PMw20afu
HqhtgE2oJLvC1a7oAdlszbfxX5K9jyM3KfJmJA9qiZq3qpzzG9aGRL3mPWWqqqPc
MinN815iMIzKixMUD9mV1KtCzd3/Csy0PzBduZTJQJyGI1AGOsSMdlJoiQ81vFYM
7crEU7LoqPKqfu+qGoC47mg58adfhEWpfHLMZagH/fuoYX0ZcPn/Yn+n7LpU3ofN
C8S+Jw3+omL4/rs602GXwjSfnfu4mtR2qp63gMTy
-----END CERTIFICATE-----
)";
